### ISSUE TITLE
Use only setup.cfg in lieu of setup.py

### ISSUE THREAD

**Issue by dataders** [firebolt-db/dbt-firebolt#24]
#20 adds a `setup.cfg` to our project even though we already have a `setup.py`. This will only cause problems for us by not having a single source of truth for package configuration. This should be addressed at somepoint

> Might be wrong here, but I'm fairly certain we don't need this file. We're currently using `setup.py` instead of a `.cfg`. [relevant SO question?](https://stackoverflow.com/questions/39484863/whats-the-difference-between-setup-py-and-setup-cfg-in-python-projects)

_Originally posted by @swanderz in https://github.com/firebolt-db/dbt-firebolt/pull/20#r754762061_

**Comment by ima-hima** [comment]
> #20 adds a `setup.cfg` to our project even though we already have a `setup.py`. This will only cause problems for us by not having a single source of truth for package configuration. This should be addressed at somepoint
> 
> > Might be wrong here, but I'm fairly certain we don't need this file. We're currently using `setup.py` instead of a `.cfg`. [relevant SO question?](https://stackoverflow.com/questions/39484863/whats-the-difference-between-setup-py-and-setup-cfg-in-python-projects)
> 
> _Originally posted by @swanderz in [#20 (comment)](https://github.com/firebolt-db/dbt-firebolt/pull/20#r754762061)_

Fully agree. I'll add a Jira todo and take care of this ASAP.

**Comment by ericf-firebolt** [comment]
Done in #33
